version: "3.8"
services:

  postgres: 
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./etc/postgres/sample.csv:/data/sample.csv
      - ./etc/postgres/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: postgres

  jupyter:
    image: marcelmaatkamp/mkdocs-jupyter-example-jupyter:${JUPYTER_VERSION}
    command: start-notebook.sh --NotebookApp.token=''
    build:
      context: etc/jupyter
      args:
        JUPYTER_VERSION: ${JUPYTER_VERSION}
        SQLALCHEMY_VERSION: ${SQLALCHEMY_VERSION}
    depends_on:
      - postgres
    ports:
      - 8888:8888
    volumes:
      - ./etc/jupyter/work:/home/jovyan/work
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      
  mkdocs:
    image: marcelmaatkamp/mkdocs-jupiter-example-mkdocs:${MKDOCS_MATERIAL_VERSION}
    depends_on:
      - jupyter
    build:
      context: etc/mkdocs
      args:
        MKDOCS_MATERIAL_VERSION: ${MKDOCS_MATERIAL_VERSION}
        SQLALCHEMY_VERSION: ${SQLALCHEMY_VERSION}      
    ports:
      - 0.0.0.0:8000:8000
    volumes:
      - ./etc/mkdocs/docs:/docs/docs
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres

  mkdocs-jupyter:
    image: marcelmaatkamp/mkdocs-jupiter-example-mkdocs:${MKDOCS_MATERIAL_VERSION}
    depends_on:
      - jupyter
    build:
      context: etc/mkdocs
      args:
        JUPYTER_VERSION: ${JUPYTER_VERSION}
        MKDOCS_MATERIAL_VERSION: ${MKDOCS_MATERIAL_VERSION}
        SQLALCHEMY_VERSION: ${SQLALCHEMY_VERSION}
    ports:
      - 8000:8000
    volumes:
      - /home/marcel/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/marcel/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ./etc/mkdocs/docs:/docs/docs
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres