version: "3.8"
services:

  postgres: 
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./etc/postgres/sample.csv:/data/sample.csv
      - ./etc/postgres/sample.sql:/docker-entrypoint-initdb.d/sample.sql

  adminer:
    image: adminer:4.8.1-standalone
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DB_DRIVER: postgres
      ADMINER_DEFAULT_DB_HOST: postgres
      ADMINER_DEFAULT_DB_NAME: postgres

  jupyter:
    command: start-notebook.sh --NotebookApp.token=''
    build:
      context: etc/jupyter
      args:
        SQLALCHEMY_VERSION: ${SQLALCHEMY_VERSION}
    depends_on:
      - postgres
    ports:
      - 8888:8888
    volumes:
      - ./etc/jupyter/work:/home/jovyan/work
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      
  mkdocs:
    # image: squidfunk/mkdocs-material:9.0.8
    depends_on:
      - jupyter
    build:
      context: etc/mkdocs
      args:
        SQLALCHEMY_VERSION: ${SQLALCHEMY_VERSION}      
    ports:
      - 8000:8000 
    volumes:
      - .:/docs
      - /home/marcel/.ssh/id_rsa:/root/.ssh/id_rsa
      - /home/marcel/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres      